### ISSUE TITLE
Order notification crash: Value was "object" expected "int" at Lunar\Base\Casts\TaxBreakdown:27

### ISSUE THREAD

**Issue by AlexDanault** [lunarphp/lunar#756] opened 2022-11-26 15:00 UTC
- Lunar version: 0.1.4
- Laravel Version: 9.30.1
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.0.28

### Expected Behaviour:

Sending mail when changing order statut from admin hub doesn't crash.

### Actual Behaviour:

Crash even for a very basic mailable

### Steps To Reproduce:

- From website, submit and pay an order
- Go to admin hub, view order
- Change status to "payment received" (yes, same status as current)
- Select the mailable to use
- Select recipients
- Send email
- Mailable crashes, and order cannot be viewed anymore without crashing

Error report: https://flareapp.io/share/lm2BqaYm#F113

Lunar order config in `config\lunar\orders.php` :
```
use App\Mail\OrderPaymentReceived;

    'statuses' => [
...(snipped)...
        'payment-received' => [
            'label' => 'Payment Received',
            'color' => '#6a67ce',
            'mailers' => [
                OrderPaymentReceived::class
            ],
            'notifications' => [],
        ],
...(snipped)...
    ],
```

Mailable class in `app\Mail\OrderPaymentReceived.php` :
```
namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class OrderPaymentReceived extends Mailable
{
    use Queueable, SerializesModels;

    public function build()
    {
        return $this->subject('ORDER PMT RVC')
            ->view('emails.order_payment_received');
    }
}
```

Mailable view in `resources\views\emails\order_payment_received.php` :
```
PMT RCV: {{ $order->reference }}

```

**Comment by alecritson** [comment] 2023-05-24 06:51
Closing as this refers to an older version of Lunar, if it's still a problem in the latest version feel free to reopen

**Closed by alecritson** 2023-05-24 06:51 UTC
Labels: bug

**Comment by rjvandoesburg** [comment] 2023-08-28 17:31
For anyone that stumbles on this same issue (like me); This is caused by Laravel Telescope when it tries to serialize certain data. When I disabled telescope no error would show. (Even when the error shows, the mail is sent)
